---
- name: test1
  box: bento/centos-8.1
  ram: 1024
  ip: 192.168.1.10
  network_type: private_network
- name: test2
  box: bento/centos-8.1
  ram: 512
  ip: 192.168.1.11
  network_type: private_network
- name: test3
  box: bento/centos-8.1
  ram: 2048
  ip: 192.168.1.12
  network_type: private_network