# this playbook is intended to deploy confluence server + mysql + nginx
---




- name: Copy SSH key and Install Nginx
  hosts: proxy-1
  become: true

  tasks:
    - name: Copy private ssh key
      authorized_key:
        user: vagrant
        state: present
        key: " {{ lookup('file','/Users/dzarpelon/.ssh/devops_key.pub') }} "
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present

    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Insert Index Page
      template:
        src: src/index.html
        dest: /usr/share/nginx/html/index.html

    - name: Start NGiNX
      service:
        name: nginx
        state: started